#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url-old = http://localhost:8080/orangehrm/orangehrm-5.8.1/web/index.php/auth/login

#Browser Configuration
browser = chrome
headless=true

#Credentials
username = orangehrm_divyadevi
password = myRiya@may2026

#ImplicitWait (in seconds)
implicitWait = 10

#ExplicitWait
explicitWait = 30